"""Strategy protocol and registry for the quant trading system."""

import threading
from typing import Protocol, runtime_checkable

from quant.models import BacktestResult, MarketContext, Signal


@runtime_checkable
class Strategy(Protocol):
    """Protocol defining the interface for trading strategies."""

    @property
    def name(self) -> str:
        """The unique name of the strategy."""
        ...

    @property
    def version(self) -> str:
        """The version of the strategy."""
        ...

    @property
    def description(self) -> str:
        """A description of what the strategy does."""
        ...

    def analyze(self, context: MarketContext) -> list[Signal]:
        """Analyze market context and generate trading signals.

        Args:
            context: The current market context containing prices and indicators.

        Returns:
            A list of trading signals generated by the strategy.
        """
        ...

    def explain(self, signal: Signal) -> str:
        """Explain the reasoning behind a trading signal.

        Args:
            signal: The signal to explain.

        Returns:
            A human-readable explanation of why the signal was generated.
        """
        ...

    def backtest(self, historical: list[MarketContext]) -> BacktestResult:
        """Backtest the strategy against historical market data.

        Args:
            historical: A list of historical market contexts.

        Returns:
            The results of the backtest.
        """
        ...


class StrategyRegistry:
    """Thread-safe registry for managing trading strategies."""

    def __init__(self) -> None:
        """Initialize an empty strategy registry."""
        self._strategies: dict[str, Strategy] = {}
        self._lock = threading.RLock()

    def register(self, strategy: Strategy) -> None:
        """Register a strategy in the registry.

        Args:
            strategy: The strategy to register.
        """
        with self._lock:
            self._strategies[strategy.name] = strategy

    def get(self, name: str) -> Strategy:
        """Get a strategy by name.

        Args:
            name: The name of the strategy to retrieve.

        Returns:
            The strategy with the given name.

        Raises:
            KeyError: If no strategy with the given name exists.
        """
        with self._lock:
            if name not in self._strategies:
                raise KeyError(f"Strategy '{name}' not found in registry")
            return self._strategies[name]

    def list_strategies(self) -> list[str]:
        """List all registered strategy names.

        Returns:
            A list of strategy names.
        """
        with self._lock:
            return list(self._strategies.keys())

    def all(self) -> list[Strategy]:
        """Get all registered strategies.

        Returns:
            A list of all registered strategies.
        """
        with self._lock:
            return list(self._strategies.values())
