"""Domain models for the quant trading system."""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, computed_field


class Action(str, Enum):
    """Trading action types."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class Signal(BaseModel):
    """A trading signal generated by a strategy."""

    ticker: str
    action: Action
    size: Decimal = Field(ge=0)
    confidence: int = Field(ge=0, le=100)
    rationale_tags: list[str] = Field(default_factory=list)
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    entry_price: Decimal | None = None
    explanation: str | None = None
    strategy_name: str | None = None
    timestamp: datetime = Field(default_factory=datetime.now)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def risk_reward_ratio(self) -> Decimal | None:
        """Calculate risk/reward ratio from entry, stop loss, and take profit.

        Returns the ratio of potential reward to potential risk.
        Returns None if any required price is missing or if risk is zero.
        """
        if self.entry_price is None or self.stop_loss is None or self.take_profit is None:
            return None

        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)

        if risk == 0:
            return None

        return reward / risk


class Position(BaseModel):
    """A position held in the portfolio."""

    ticker: str
    quantity: Decimal
    avg_price: Decimal = Field(ge=0)
    current_price: Decimal | None = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def market_value(self) -> Decimal | None:
        """Calculate the current market value of the position."""
        if self.current_price is None:
            return None
        return self.quantity * self.current_price

    @computed_field  # type: ignore[prop-decorator]
    @property
    def unrealized_pnl(self) -> Decimal | None:
        """Calculate unrealized profit/loss."""
        if self.current_price is None:
            return None
        return self.quantity * (self.current_price - self.avg_price)


class MarketContext(BaseModel):
    """Market context containing portfolio state and market indicators."""

    timestamp: datetime = Field(default_factory=datetime.now)
    cash: Decimal = Field(ge=0)
    positions: list[Position] = Field(default_factory=list)
    futures_signal: float = Field(ge=-1, le=1)
    vix: float | None = None
    watchlist_sentiment: dict[str, Any] = Field(default_factory=dict)
    indicators: dict[str, Any] = Field(default_factory=dict)
    news: dict[str, Any] = Field(default_factory=dict)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total_equity(self) -> Decimal:
        """Calculate total equity (cash + sum of position market values)."""
        position_value = Decimal(0)
        for position in self.positions:
            if position.market_value is not None:
                position_value += position.market_value
        return self.cash + position_value


class BacktestResult(BaseModel):
    """Results from a backtest run."""

    total_return: Decimal
    total_trades: int = Field(ge=0)
    winning_trades: int = Field(ge=0)
    losing_trades: int = Field(ge=0)
    gross_profit: Decimal = Field(ge=0)
    gross_loss: Decimal = Field(ge=0)
    max_drawdown: Decimal
    sharpe_ratio: float | None = None
    trades: list[dict[str, Any]] = Field(default_factory=list)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def win_rate(self) -> float | None:
        """Calculate the win rate as a percentage."""
        if self.total_trades == 0:
            return None
        return (self.winning_trades / self.total_trades) * 100

    @computed_field  # type: ignore[prop-decorator]
    @property
    def profit_factor(self) -> float | None:
        """Calculate profit factor (gross profit / gross loss).

        Returns None if there are no losses.
        """
        if self.gross_loss == 0:
            return None
        return float(self.gross_profit / self.gross_loss)
